#!/bin/bash
if [ $# -gt 2 ]; then
	echo "Remove SSH IP from white list"
	echo
	echo "usage: ${0} [IP] [SSH_PORT]"
	echo
	echo "If IP and/or SSH_PORT are not given IP and/or SSH_PORT from \$SSH_CLIENT will be used."
	echo
	exit 1
fi
if [ $# -eq 0 ]; then
	IP="$(echo $SSH_CLIENT | cut -d' ' -f1)"
	echo "No IP given using IP from \$SSH_CLIENT (${IP})"
	SSH_PORT="$(echo $SSH_CLIENT | cut -d' ' -f3)"
elif [ $# -eq 1 ]; then
	IP="${1}"
	SSH_PORT="$(echo $SSH_CLIENT | cut -d' ' -f3)"
	#SSH_PORT="$(grep -E '^Port [0-9]+' /etc/ssh/sshd_config | grep -oE '[0-9]+' | head -n1)"
else
	IP="${1}"
	SSH_PORT="${2}"
fi
firewall-cmd --permanent --direct --remove-rule ipv4 filter INPUT_direct 0 -p tcp -s "${IP}" --dport "${SSH_PORT}" -m state --state NEW -j ACCEPT
firewall-cmd --reload
systemctl restart fail2ban

